# fly.toml file for your app

app = "hospedar"  # Nome da sua aplicação no Fly.io

[build]
  builder = "heroku/builder:20-cnb"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  http_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
