# fly.toml file for your app

app = "final-grerhq"  # Nome da sua aplicação no Fly.io

[build]
  builder = "heroku/builder:20"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  http_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
