# fly.toml file for your app

app = "hospedar"  # Nome da sua aplicação no Fly.io

[build]
  builder = "heroku/builder:20"
[processes]
app = "uvicorn main:app --host 0.0.0.0 --port 8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  http_checks = []

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
