[build]
  builder = "heroku/builder:20"

[processes]
  app = "uvicorn Back.main:app --host 0.0.0.0 --port 8080"  # Corrigir a referência para a pasta Back

[[services]]
  internal_port = 8080
  processes = ["app"]
  [[services.ports]]
    handlers = ["http"]
    port = 80

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
